# Generated by Django 2.2.16 on 2021-12-29 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_loans', '0003_auto_20211229_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='amount',
        ),
    ]
