# Generated by Django 2.2.16 on 2021-12-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_loans', '0006_fundapplication_loanapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='amount',
        ),
        migrations.AddField(
            model_name='fundapplication',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
