# Generated by Django 2.2.16 on 2021-12-31 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_loans', '0007_auto_20211231_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundapplication',
            old_name='loan',
            new_name='fund',
        ),
    ]
