# Generated by Django 2.2.16 on 2021-12-31 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_provideruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='provideruser',
            name='fund',
        ),
    ]
